[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  links2004/WebSockets@^2.6.1
build_flags =
  -D WIFI_SSID=\"ROBOBET_WIFI\"
  -D WIFI_PASSWORD=\"ROBOBET_PASS\"
  -D WIFI_CONNECT_TIMEOUT_MS=12000
  -D ROBOBET_SERVER_HOST=\"192.168.1.100\"
  -D ROBOBET_SERVER_PORT=8000
  -D CAMERA_TRANSPORT_HTTP=1
  -D CAMERA_TRANSPORT_UART=0
  -D CAMERA_HTTP_HOST=\"192.168.1.56\"
  -D CAMERA_HTTP_TIMEOUT_MS=2800
  -D CAMERA_HTTP_PORT=80
  -D CAMERA_UART_RX=16
  -D CAMERA_UART_TX=4
  -D CAMERA_UART_BAUD=115200
