[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
build_flags =
  -D BOARD_HAS_PSRAM
  -mfix-esp32-psram-cache-issue
  -D WIFI_SSID=\"MyHome\ P2\"
  -D WIFI_PASSWORD=\"IEE\ 2018\"
  -D CAMERA_USE_STATIC_IP=1
  -D CAMERA_STATIC_IP=\"192.168.1.56\"
  -D CAMERA_GATEWAY_IP=\"192.168.1.1\"
  -D CAMERA_SUBNET_MASK=\"255.255.255.0\"
  -D CAMERA_SERIAL_REPORTS=0
